### PR TITLE
Child account management

### PR DESCRIPTION
**Pull request by BNMoyers**
# Description
  This PR handles the Children table and the routes, models, and middleware related to said table. 
Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

- [x] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [x] Tested Parent Routes
- [x] Tested Child Routes

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by Forrestdarabian — APPROVED** [review]
Code looks clean and well organized, good work on CRUD functionality

**Review by ghost — APPROVED** [review]
clean code

**Review by ghost — COMMENTED** [review]
imported children routes

**Review by ghost — COMMENTED** [review]
can add put and deleted for child by id

**Comment by EricBanker12** [comment]
[[Parent] - Manage my children's account and preferences](https://trello.com/c/gLrPV5Wd/21-parent-manage-my-childrens-account-and-preferences)

**Review by ghost — COMMENTED** [review]
merging and cleaning up of code.

**Review by ghost — COMMENTED** [review]
child table.

**Review by ghost — COMMENTED** [review]
parent routes made with add child feature.

**Review by ghost — COMMENTED** [review]
get for children.

**Review by ghost — COMMENTED** [review]
token for add child

**Review by ghost — COMMENTED** [review]
rebasing of code and all CRUD operations done.

**Review by ghost — COMMENTED** [review]
added preferences route for the child.

**Review by ghost — COMMENTED** [review]
rebasing the middleware

**Review by ghost — COMMENTED** [review]
rebasing of middleware

**Review by ghost — COMMENTED** [review]
successfully deleted.

**Review by EricBanker12 — APPROVED** [review]
I think comments could help validate.middleware simply due to its length, but for everything else, I found the naming descriptive enough. 

Everything appeared to run locally and all tests passed.

**Review by wSedlacek — APPROVED** [review]

**Pull request merged**
