### PR TITLE
Revert "Db entity mechanics"

### PR DESCRIPTION
**Pull request by grifmang**
Reverts Lambda-School-Labs/story-squad-be#26

### CODE REVIEW

**Review by DeusExMashima — COMMENTED** [review]
i think this looks fine

**Review by itshui3 — APPROVED** [review]
Looks good

**Review by DeusExMashima — APPROVED** [review]
correct me if i am wrong but i think everything looks fine if you want to revert everything back

This would:

- remove pip file & pipfile.lock
- move files out of folders to its original places (entities)
- remove DS integration and revert everything back to previous submission routes

**Review by squashgray — COMMENTED** [review]
I categorically approve this

**Pull request merged**
